### ISSUE TITLE
Bug(?) in calculating errors

### ISSUE THREAD

**Issue by Fellow-baka** [wojdyr/fityk#31]
Dear Marcin,

I think there is a bug in calculating errors. It seems like the calculation takes into account other datasets.

How to reproduce:
1. Load any dataset, add function, e.g. Lorentzian.
2. Fit, check `info peaks_err`. Note the error value, in my case: 9880.27 +/- 538.262
3. Access the same value and it's error through `print F[0].height` (9880.27) `print F[0].height.error` (538.262)
4. Add a new dataset (same data).
5. Check `info peaks_err` for old dataset, not that error value the same: 9880.27 +/- 538.262
6. Access the same value and it's error through `print F[0].height` (9880.27) `print F[0].height.error` (2947.07)
7. Note that error is different. Selection of a particular dataset through `@0: print F[0].height.error` does not change anything.

Is it intended behavior?

Fityk version 1.3.1 win.

**Comment by wojdyr** [comment]
The other datasets are taken into account because in general you may use the same variable in multiple datasets. The error is different if we refine a single dataset in isolation, and if we refine all datasets together.

I understand this is confusing, it was brought up before, for example here:
https://groups.google.com/forum/#!topic/fityk-users/mVViB39j-tE

**Comment by Fellow-baka** [comment]
So, is there a way to obtain exactly the same value of error estimate as in `info_peaks_err`, but for a particular function in case of many datasets?
